### ISSUE TITLE
Monkey patching current node

### ISSUE THREAD

**Issue by Nokel81** [livinginthepast/ipaddr_extensions#4]
I have several cookbooks that are now failing because of the multiple nodes error. Would it be possible for me to get an explanation of what this error means and maybe some tips on how to avoid it?

**Comment by sax** [comment]
Can you please post the error message that you're seeing?

**Comment by Nokel81** [comment]
```
      Reloading node attributes

       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/ipaddr_extensions/libraries/gem_installation.rb
       ================================================================================

       RuntimeError
       ------------
       Whoops! Expected to monkey patch only the current node, found multiple

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/ipaddr_extensions/libraries/gem_installation.rb:29:in `rescue in <top (required)>'
         /tmp/kitchen/cache/cookbooks/ipaddr_extensions/libraries/gem_installation.rb:1:in `<top (required)>'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/ipaddr_extensions/libraries/gem_installation.rb:

        22:    require 'ipaddr_extensions'
        23:    require 'ohai'
        24:
        25:    puts "Reloading node attributes"
        26:    ohai = ::Ohai::System.new
        27:    ohai.all_plugins
        28:    count = ObjectSpace.each_object(Chef::Node) { |n| n.automatic_attrs.merge! ohai.data }
        29>>   raise "Whoops! Expected to monkey patch only the current node, found multiple" if count > 1
        30:  end
        31:


       Running handlers:
       [2018-01-12T20:33:08+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2018-01-12T20:33:08+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 45 seconds
       [2018-01-12T20:33:08+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2018-01-12T20:33:08+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2018-01-12T20:33:08+00:00] ERROR: Whoops! Expected to monkey patch only the current node, found multiple
       [2018-01-12T20:33:09+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by sax** [comment]
This is pretty weird. I've been unable to reproduce it... can you please provide a bit more information to help me debug?

* Chef version
* Ohai version
* OS

Also, how are you installing Chef? Is this from a particular omnibus, or are you using opsworks? Is there anything special about your setup (or anything that changed) where a single chef node would have multiple Node objects?

Thanks!

**Comment by Nokel81** [comment]
chef -v
```
Chef Development Kit Version: 2.4.17
chef-client version: 13.6.4
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.19.2
inspec version: 1.45.13
```

ohai -v
```
Ohai: 13.6.0
```

os
```
macOS High Sierra
version 10.13.2 (17C205)
```

**Comment by Nokel81** [comment]
```-----> Starting Kitchen (v1.19.2)
-----> Creating <access-ubuntu-docker>...
       Sending build context to Docker daemon  22.71MB
       Step 1/18 : FROM phusion/baseimage:0.9.18
        ---> 772dd063a060
       Step 2/18 : RUN rm -f /etc/service/sshd/down
        ---> Using cache
        ---> 423460a8b562
       Step 3/18 : RUN DEBIAN_FRONTEND=noninteractive apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get install -y         curl         build-essential
        ---> Using cache
        ---> 52b35e59bf4a
       Step 4/18 : EXPOSE 22
        ---> Using cache
        ---> 852d9d0a5d7d
       Step 5/18 : ENV DEBIAN_FRONTEND noninteractive
        ---> Using cache
        ---> f60373412765
       Step 6/18 : ENV container docker
        ---> Using cache
        ---> 92c0c9f1f022
       Step 7/18 : RUN apt-get update
        ---> Using cache
        ---> f08ea2f60eb4
       Step 8/18 : RUN apt-get install -y sudo openssh-server curl lsb-release
        ---> Using cache
        ---> c8a825881415
       Step 9/18 : RUN if ! getent passwd self; then                 useradd -d /home/self -m -s /bin/bash -p '*' self;               fi
        ---> Using cache
        ---> 94d8d08642f9
       Step 10/18 : RUN echo "self ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        ---> Using cache
        ---> e3f87ed76055
       Step 11/18 : RUN echo "Defaults !requiretty" >> /etc/sudoers
        ---> Using cache
        ---> ab08ca6622c9
       Step 12/18 : RUN mkdir -p /home/self/.ssh
        ---> Using cache
        ---> 6ec78a5bde11
       Step 13/18 : RUN chown -R self /home/self/.ssh
        ---> Using cache
        ---> 5ce90068dcbc
       Step 14/18 : RUN chmod 0700 /home/self/.ssh
        ---> Using cache
        ---> 09a690822e82
       Step 15/18 : RUN touch /home/self/.ssh/authorized_keys
        ---> Using cache
        ---> 2c6c5b18af71
       Step 16/18 : RUN chown self /home/self/.ssh/authorized_keys
        ---> Using cache
        ---> e15b1ea251c3
       Step 17/18 : RUN chmod 0600 /home/self/.ssh/authorized_keys
        ---> Using cache
        ---> a89001363257
       Step 18/18 : RUN echo ecdsa-sha2-nistp256\ d14a028c2a3a2bc9476102bb288234c415a2b01f828ea62ac5b3e42f\=\ chef-kitchen >> /home/self/.ssh/authorized_keys
        ---> Using cache
        ---> 3dd8ecc8b529
       Successfully built 3dd8ecc8b529
       ae22a72d7b35d54bee3eb354388a5ea48e1c69b83dfc30d14601919cb66baad7
       0.0.0.0:32780
       0.0.0.0:32781
       Waiting for SSH service on localhost:32780, retrying in 3 seconds
       [SSH] Established
       Finished creating <access-ubuntu-docker> (0m5.17s).
-----> Converging <access-ubuntu-docker>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 6.3.1...
       Removing non-cookbook files before transfer
       Preparing data_bags
       Preparing environments
       Preparing nodes
       Preparing roles
       Preparing secret
       Preparing validation.pem
       Preparing client.rb
-----> Installing Chef Omnibus (12.6)
       Downloading https://omnitruck.chef.io/install.sh to file /tmp/install.sh
       Trying curl...
       Download complete.
       ubuntu 14.04 x86_64
       Getting information for chef stable 12.6 for ubuntu...
       downloading https://omnitruck.chef.io/stable/chef/metadata?v=12.6&p=ubuntu&pv=14.04&m=x86_64
         to file /tmp/install.sh.37/metadata.txt
       trying curl...
       sha1	8465cb169320e3c913a45109597e449f289549ac
       sha256	e0b42748daf55b5dab815a8ace1de06385db98e29a27ca916cb44f375ef65453
       url	https://packages.chef.io/files/stable/chef/12.6.0/ubuntu/14.04/chef_12.6.0-1_amd64.deb
       version	12.6.0
       downloaded metadata file looks valid...
       downloading https://packages.chef.io/files/stable/chef/12.6.0/ubuntu/14.04/chef_12.6.0-1_amd64.deb
         to file /tmp/install.sh.37/chef_12.6.0-1_amd64.deb
       trying curl...
       Comparing checksum with sha256sum...
       Installing chef 12.6
       installing with dpkg...
       Selecting previously unselected package chef.
(Reading database ... 18795 files and directories currently installed.)
       Preparing to unpack .../chef_12.6.0-1_amd64.deb ...
       Unpacking chef (12.6.0-1) ...
       Setting up chef (12.6.0-1) ...
       Thank you for installing Chef!
       Transferring files to <access-ubuntu-docker>
       Starting Chef Client, version 12.6.0
       Creating a new client identity for access-ubuntu-docker using the validator key.
       resolving cookbooks for run list: ["self::access", "self::kitchen_test"]
       Synchronizing Cookbooks:
         - sudo (4.0.0)
         - user (0.7.0)
         - openssh (2.6.1)
         - openssl (8.0.0)
         - mercurial (2.0.4)
         - mongodb (0.16.2)
         - nginx (7.0.0)
         - nvm (0.1.7)
         - nodejs (5.0.0)
         - rabbitmq (5.4.0)
         - iptables-ng (3.0.0)
         - sensu (4.1.0)
         - runit (1.7.8)
         - python (1.4.6)
         - hostsfile (3.0.1)
         - ssh_authorized_keys (0.4.0)
         - tar (2.1.1)
         - parted (2.1.4)
         - rsyslog (4.0.0)
         - logrotate (2.2.0)
         - apt (6.1.4)
         - encrypted_volume (0.1.0)
         - chef-vault (2.1.1)
         - timezone-ii (0.2.0)
         - ntp (3.5.4)
         - java (1.50.0)
         - git (8.0.0)
         - squid (4.0.1)
         - grafana2 (0.1.9)
         - postgresql (6.1.1)
         - slack (0.1.3)
         - slack_handler (0.9.1)
         - elasticsearch (3.4.3)
         - openswan (0.3.2)
         - sysctl (0.7.0)
         - mongodb3 (5.3.0)
         - build-essential (8.0.1)
         - sc-mongodb (0.18.1)
         - composer (2.6.0)
         - chef_client_updater (3.1.3)
         - php (4.0.0)
         - docker (2.15.26)
         - unattended-upgrades (0.1.2)
         - iptables (4.3.1)
         - windows (3.4.3)
         - ohai (4.1.0)
         - yum-epel (2.1.2)
         - yum (5.1.0)
         - compat_resource (12.19.0)
         - zypper (0.4.0)
         - ark (3.1.0)
         - yum-erlang_solutions (1.0.3)
         - dpkg_autostart (0.2.0)
         - erlang (5.1.0)
         - ms_dotnet (4.0.1)
         - redisio (2.6.1)
         - homebrew (4.2.0)
         - packagecloud (0.3.0)
         - ipaddr_extensions (0.3.1)
         - chef_handler (2.1.2)
         - chef-sugar (3.6.0)
         - seven_zip (2.0.2)
         - xml (3.1.2)
         - mingw (2.0.1)
         - mysql (8.5.1)
         - ulimit (0.4.0)
         - selinux_policy (2.0.1)
       Compiling Cookbooks...
Fetching: ipaddr_extensions-1.0.2.gem (100%)
```

**Comment by Nokel81** [comment]
I have installed chef through `brew cask`

**Comment by sax** [comment]
Thank you for these full logs! I wonder if there might be an issue with the local chef client being version 13, but the chef client in your container being version 12... I'll see if I can get a reproduction case nailed down.

**Comment by Nokel81** [comment]
If this helps, the problem seems to go away if I run the converge command again on the same recipe  without destroying it, but that seems doesn't look like a fix.

**Comment by sax** [comment]
Yeah, it should only be happening when the ipaddr_extensions gem is
installed into the container. On later runs, that step is skipped.

If that code does not run, though, on the first run you won’t have access
to private ip scopes during attribute resolution.

**Comment by Nokel81** [comment]
So by that do you mean that this package is included by default? Because I couldn't find anything that depends on it.

**Comment by sax** [comment]
No, only a cookbook that relies on the ipscopes Ohai plugin should depend
on this cookbook.

**Comment by Nokel81** [comment]
I believe that I have made a MFP.

yml:
```yml
platforms:
  - name: ubuntu-docker
    driver_config:
      # dirty trick: to get extra docker commands
      image: |
        phusion/baseimage:0.9.18
        # 0.9.19+ are ubuntu 16.04
        RUN rm -f /etc/service/sshd/down
        RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
            DEBIAN_FRONTEND=noninteractive apt-get install -y \
                curl \
                build-essential
        EXPOSE 22
    driver:
      name: docker
      # because osx, on linux add your user to the DOCKER group
      use_sudo: false
      forward:
        # ssh
        - 22
        - 80
        - 443
verifier:
  name: inspec
suites:
  - name: test
    provisioner:
      name: chef_zero
      require_chef_omnibus: 12.6
      nodes_path: './nodes'
      client_rb:
        environment: testing
    driver_config:
      username: test
    data_bags_path: './data_bags'
    root_path: '.'
    run_list:
      - 'recipe[testbook::test]'
```

testbook::test
```rb
user 'kitchen' do
    home '/home/kitchen'
    shell '/bin/bash'
    manage_home true
end

sudo 'kitchen' do
    user 'kitchen'
    nopasswd true
end
```

**Comment by Nokel81** [comment]
Another thing that I have noticed is that if I add the following code to the top of a recipe

```ruby
ObjectSpace.each_object(Chef::Node) {
    |n|
    log "counting" do
        message "Hello"
        level :warn
    end
}
```

Then I only get one message printed, not more than 1 which would be implied by the error (this is after running the converge once already)

**Comment by sax** [comment]
Can you print out the count of nodes? I still can't reproduce in my kitchen setup, but I've verified that adding inspec does not cause the problem. I'm still running in vagrant, though, so my next step is to use docker.

**Comment by sax** [comment]
Hmmm... the problem with using `kitchen-docker` is that I can't define a private IP address for the cookbook's test suite to verify. It winds up failing [here](https://github.com/livinginthepast/ipaddr_extensions/blob/master/test/integration/cookbooks/test_cookbook/recipes/default.rb#L9) inside the cookbook's test suite. 

It still does not raise because of multiple `Chef::Node` instance in the object space, though.

**Comment by Nokel81** [comment]
Would that be the following part of the yml file?

```yml
      network:
        - ['private_network', {ip: '192.168.2.2'}]
```

**Comment by Nokel81** [comment]
How would I go about printing the count of the nodes? I would have to inject some lines before the "Reloading node attributes" line is printed

**Comment by sax** [comment]
You can change the line the raises to this:

```
  raise "Whoops! Expected to monkey patch only the current node, found #{count}" if count > 1
```

So my worry about just taking that out is that we're trying to reload Ohai data before attribute resolution. If there is more than one node, then it's unclear what is being monkey patched... there really should only be a single node at that point.

**Comment by Nokel81** [comment]
If my suite downloads ipaddr_extensions fresh every time, how would I go about changing it? I didn't know that that was possible

**Comment by sax** [comment]
Oh... do you have a local checkout in your Berks cache? The way `kitchen-vagrant` works is to ship in dependencies from the local cache. I would assume that docker plugins would work the same, though I could very well be wrong about that.

**Comment by Nokel81** [comment]
`Whoops! Expected to monkey patch only the current node, found 2`

**Comment by Nokel81** [comment]
I added a `puts n` in the `for_each` and the following was produced
```
node[test-ubuntu-1404]
node[]
```

**Comment by sax** [comment]
That is so weird. Maybe there’s something else in the node object that can
show what the second one is.

**Comment by Nokel81** [comment]
I printed out the JSON representation of each of the nodes and then used `diff` and these are the noticeable different parts.

```
"name": "test-ubuntu-1404",                          "name": null,
"chef_environment": "website_staging",               "chef_environment": "_default",
...                                                  ...
"init_package": "init",                              "init_package": "init"
"recipes": [
    "test::kitchen_test",
    "timezone-ii",
    "timezone-ii::default",
    "ntp",
    "ntp::default",
    "test::access",
    "test::test_repo",
    "test::nginx_website"
],
"expanded_run_list": [
    "test::kitchen_test",
    "timezone-ii::default",
    "ntp::default",
    "test::access",
    "test::test_repo",
    "test::nginx_website"
],
"roles": [
    "website"
],
"cookbooks": {
    "timezone-ii": { "version": "0.2.0" },
    "ntp": { "version": "3.5.4" },
    "sudo": { "version": "4.0.0" },
    "user": { "version": "0.7.0" },
    "openssh": { "version": "2.6.1" },
    "openssl": { "version": "8.0.0" },
    "mercurial": { "version": "2.0.4" },
    "mongodb": { "version": "0.16.2" },
    "nginx": { "version": "7.0.0" },
    "nodejs": { "version": "5.0.0" },
    "nvm": { "version": "0.1.7" },
    ...
    "ipaddr_extensions": {  "version": "0.3.1" },
    ...
},
"privateaddress": "192.168.0.100"
...                                                  ...
"run_list": [                                        "run_list": []
    "recipe[sensibill::kitchen_test]",
    "role[website]"
]
```

**Comment by sax** [comment]
Awesome, that gives me something to work with. I'll throw out nodes with a null name.

**Comment by Nokel81** [comment]
Yup, I did that locally and it worked. Still don't know why or how it is being created but as long as it works all good.

**Comment by sax** [comment]
Thank you for bearing with me and providing so much helpful information. I just pushed a new version to github and to supermarket. Let me know if that works for you, and I'll close this issue.

**Comment by Nokel81** [comment]
Yup all good, thank you
